apiDefinitions: 
  api: spec/swagger.yaml
# items with `#CE` are supported in the community edition of Redoc
doNotResolveExamples: true
referenceDocs:

  # search:

  disableSearch: false  # CE # disable search indexing and hide search box.
  searchOperationTitleBoost: 4 # Boost coefficient for search terms found in operation titles. The bigger value is,
                               # the higher searches will rank.
  searchTagTitleBoost: 8 # Boost coefficient for search terms found in operation titles.
  searchFieldLevelBoost: 0.95 # Boost coefficient for search terms found in field at specific level (if less than 1 searches found deeper would rank lower).
  searchMode: "default" # The search indexing mode. Can be also "path-only" – the index and search only operation paths.
  ctrlFHijack: true # Brings focus to the search bar when control-F is pushed.

  # expansions:

  expandDefaultServerVariables: false  # CE # enable expanding default server variables
  expandResponses: ""  # CE # specify which responses to expand by default by response codes.
                              # Values should be passed as comma-separated list without spaces e.g. expandResponses="200,201".
                              # Special value "all" expands all responses by default.
                              # Be careful: this option can slow-down documentation rendering time
  jsonSampleExpandLevel: 2  # CE # set the default expand level for JSON payload samples (responses and request body).
                          # Special value 'all' expands all levels

  # sort

  requiredPropsFirst: false # CE  # show required properties first ordered in the same order as in required array.
  sortPropsAlphabetically: false # CE  # sort properties alphabetically.
  payloadSampleIdx: 0 # CE   # if set, payload sample will be inserted at this index or last. Indexes start from 0.

  # Toggle visibility of UI elements

  hideInfoSection: false # Hides the entire info section of the API definition when true.
  hideDownloadButton: false  # CE # do not show "Download" spec button. THIS DOESN'T MAKE YOUR DEFINITION PRIVATE, it just hides the button.
  hideHostname: false  # CE # if set to true, the protocol and hostname is not shown in the operation definition.
  hideLoading: false  # CE # do not show loading animation. Does not apply to CLI or Workflows rendered docs
  hideSingleRequestSampleTab: false  # CE # do not show the request sample tab for requests with only one sample.
  hideRequestPayloadSample: false # CE # Do not show request payload examples.
  menuToggle: true  # CE # if true clicking second time on expanded menu item will collapse it.
  nativeScrollbars: false # use native scrollbar for sidemenu instead of perfect-scroll
                          # (scrolling performance optimization for big definitions).
  noAutoAuth: false  # CE # do not inject Authentication section automatically.
  onlyRequiredInSamples: false  # CE # shows only required fields in request samples.
  pathInMiddlePanel:  false  # CE # show path link and HTTP verb in the middle panel instead of the right one.
  scrollYOffset: 0 # CE  # If set, specifies a vertical scroll-offset. This is often useful when there are
                   # fixed positioned elements at the top of the page, such as navbars, headers etc;
                   # scrollYOffset can be specified in various ways:
                   #  - number: A fixed number of pixels to be used as offset.
                   #  - css selector: selector of the element to be used for specifying the offset. The distance from the top of the page to the element's bottom will be used as offset.
                   #  - function (advanced): A getter function. Must return a number representing the offset (in pixels).

  showExtensions: false # CE  # show vendor extensions ("x-" fields). Extensions used by ReDoc are ignored.
                        # Can be boolean or an array of string with names of extensions to display.

  untrustedSpec: false # CE  # if set, the spec is considered untrusted and all HTML/markdown is sanitized to prevent XSS
  htmlTemplate: "./web/index.html" # CE  # Path to the optional HTML file used to modify the layout of the reference docs page.

  # Premium Feature options

  showConsole: true # Enable the API Console (the Try it functionality).
  hideLogo: false # Hide API Logo from x-logo vendor extension
  layout:
    scope: section # Controls the scope of the simultaneously rendered items.
                   # - all – render all the items.
                   # - section – render one tag at the moment
                   # - item – render one item (operation) at the moment.
    markdownItemsScope: all # Controls the scope of the simultaneously rendered items populated from the markdown description
                            # all – render all the items (default if layout.scope is "all" or "section")
                            # section – render one section (top level heading) at the moment (default if layout.scope is "item").
    showTag: true # Indicate whether to show the tag description on each endpoint page. Applicable only when layout.scope is "item".
    showInfoOnEachPage: false # Indicate whether to show the API info (version, title, download button) on each page. If set to false, it will be shown only on the first page.
    showNextButton: false # Indicate whether to show the "Next to ..." button at the end of each section.
  routingStrategy: browser # Routing strategy. "hash" – URL-fragment based, "browser" – pushState/popState-based (must be used with layout scope section or item)
  routingBasePath: "" # The base path for the PushState-based routing strategy.
  sideNavStyle: "summary-only" # style of sidenav items. Can be also "path-first" – Show the path first, and then show the summary below.
  unstable_ignoreMimeParameters: false # Apply workaround to ignore the `charset=utf` in mime-type.
  corsProxyUrl: "" # Controls whether the requests sent from the API Console (the Try it functionality) should go through a CORS proxy. To use the Redocly CORS proxy, set "https://cors.redoc.ly" as the value. Alternatively, set the URL of your own CORS proxy server as the value. The showConsole option must be enabled for this feature to work.
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: "curl"
      - lang: "Node.js" 
      - lang: "JavaScript"
      - lang: "Python"
      - lang: "C#" # Can be one of the following supported languages: "curl", "Node.js", "JavaScript", "Python", "C#".
    skipOptionalParameters: false # When enabled, optional parameters cookies, headers and query params are not included in generated code samples.